name: Linux

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:43

    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu

    env:
      PKG_CONFIG_ALLOW_CROSS: 1
      CARGO_TERM_COLOR: always
      BIN_NAME: listenmoe

    steps:
      - name: Install build deps
        run: |
          dnf -y update
          dnf -y install \
            mold alsa-lib-devel libgpg-error-devel clang pkg-config nettle-devel \
            cairo-devel gcc git glib2-devel gtk4-devel libadwaita-devel make \
            openssl-devel pango-devel pkg-config pkgconf-pkg-config \
            rustup

          rustup-init -y --profile minimal --default-toolchain stable
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          "$HOME/.cargo/bin/rustup" target add x86_64-unknown-linux-gnu
          "$HOME/.cargo/bin/rustup" target add aarch64-unknown-linux-gnu

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Build (release)
        run: cargo build --release --target ${{ matrix.target }} --features setup

      - name: List produced binary
        run: ls -R target/${{ matrix.target }}/release

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BIN_NAME }}-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/${{ env.BIN_NAME }}

      - name: Mark workspace as safe for git
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - run: echo "LATEST_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.LATEST_TAG }}
          files: target/${{ matrix.target }}/release/${{ env.BIN_NAME }}
          overwrite_files: true
