name: Linux

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu

    runs-on: ${{ matrix.os }}
    container:
      image: fedora:43

    env:
      PKG_CONFIG_ALLOW_CROSS: 1
      CARGO_TERM_COLOR: always
      BIN_NAME: listenmoe

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Resolve tag to use
        run: |
          dnf install -y git
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

          echo "--- tags ---"
          git tag --list

          echo "--- describe ---"
          TAG=$(git describe --tags --abbrev=0)
          echo "Using tag from git describe: $TAG"

          # export for later steps
          echo "LATEST_TAG=$TAG" >> "$GITHUB_ENV"

      - name: Install build deps
        run: |
          dnf -y update
          dnf -y install \
            mold alsa-lib-devel libgpg-error-devel clang pkg-config nettle-devel \
            cairo-devel gcc git glib2-devel gtk4-devel libadwaita-devel make \
            openssl-devel pango-devel pkg-config pkgconf-pkg-config \
            rustup

          rustup-init -y --profile minimal --default-toolchain stable
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          "$HOME/.cargo/bin/rustup" target add x86_64-unknown-linux-gnu
          "$HOME/.cargo/bin/rustup" target add aarch64-unknown-linux-gnu

      - name: Build (release)
        run: cargo build --release --target ${{ matrix.target }} --features setup

      - name: List produced binary
        run: ls -R target/${{ matrix.target }}/release

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BIN_NAME }}-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/${{ env.BIN_NAME }}

      - name: Show tag we will release
        run: echo "Releasing tag: ${{ env.LATEST_TAG }}"

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.LATEST_TAG }}
          files: target/${{ matrix.target }}/release/${{ env.BIN_NAME }}
          overwrite_files: true
