name: Linux

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:43

    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu

    env:
      CARGO_TERM_COLOR: always
      BIN_NAME: listenmoe

    steps:
      - name: Install build deps
        run: |
          dnf -y update
          dnf -y install \
            git \
            gcc \
            clang \
            pkg-config \
            make \
            rust cargo \
            gtk4-devel \
            libadwaita-devel \
            alsa-lib-devel \
            glib2-devel

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build (release)
        run: cargo build --release --target ${{ matrix.target }}

      - name: List produced binary
        run: ls -R target/${{ matrix.target }}/release

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BIN_NAME }}-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/${{ env.BIN_NAME }}

      - name: Get latest tag
        run: |
          latest_tag=$(git describe --tags "$(git rev-list --tags --max-count=1)")
          echo "Latest tag: $latest_tag"
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.LATEST_TAG }}
          files: target/${{ matrix.target }}/release/${{ env.BIN_NAME }}
          overwrite_files: true
